[package]

name = "nun-db"
version = "0.0.1"
authors = [ "Mateus Freira <mateus.freira@gmail.com>" ]
edition = "2018"

[dependencies]
tokio = "0.1.13"
futures = "0.3.1"
ws = "*"
env_logger = "*"
rustc-serialize = "*"
bincode = "*"
serde = "*"
timer = "*"
chrono = "*"
thread-id = "*"
tiny_http = "*"
clap = "*"
reqwest = { version="*" , features = ["blocking"]}
[dev-dependencies]
tokio-test = "*"
